test = input('Digite uma informação/ valor: ')
print('O tipo da sua informação é: {}' .format(type(test)))
print('É um número inteiro?\n', test.isnumeric())
print('É alfabético?\n', test.isalpha())
print('É alfanumérico?\n', test.isalnum())
print('É um número decimal?\n', test.isdecimal())
print('Está capitalizado?\n', test.istitle())
print('Está todo em maiúsculo?\n', test.isupper())
print('Está todo em minúsculo?\n', test.islower())
print('Só tem espaço?\n', test.isspace())